# This file adheres to the YAML5 style.
{
  name: "Go",
  on: ["push", "pull_request"],
  jobs: {
    build: {
      name: "Build",
      "runs-on": "ubuntu-latest",
      steps: [
        {
          name: "Set up Go 1.13",
          uses: "actions/setup-go@v1",
          "with": {"go-version": 1.13},
          id: "go",
        },
        {name: "Check out code into the Go module directory", uses: "actions/checkout@v1"},
#        {name: "Tests and lints", run: "make check"},
        {
          name: "Run linter over test",
          run: "make -i stat",
        },
        {
          id: get-comment-body,
          run:
            "body=$(go run ./src/cmd/stat)
            echo ::set-output name=body::$body"
        },
        {
          name: "Create commit comment",
          uses: "peter-evans/commit-comment@v1",
          "with": {
            body: ${{ steps.get-comment-body.outputs.body }},
          },
        },
      ],
    },
  },
}
