# This file adheres to the YAML5 style.
{
  name: "Go",
  on: [ "push", "pull_request" ],
  jobs: {
    build: {
      name: "Build",
      "runs-on": "ubuntu-latest",
      steps: [
        {
          name: "Set up Go 1.13",
          uses: "actions/setup-go@v1",
          "with": { "go-version": 1.13 },
          id: "go",
        },
        {
          name: "Check out code into the Go module directory",
          uses: "actions/checkout@v1",
        },
        {
          name: "Coverage",
          run: "make cover",
        },
        {
          name: "Upload coverage to Codecov",
          uses: "codecov/codecov-action@v1",
        },
      ],
    },
  },
}
